# Generated by Django 4.1.6 on 2023-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinehomeservice_app', '0002_creditcard_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='register1',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
